language: python
python:
  - '3.5'
  - '3.6'
# command to install dependencies
install:
  - pip install .[test]
# command to run tests
script:
  - pytest --cov=./
  - codecov
notifications:
    email: false
